### ISSUE TITLE
Desktop version

### ISSUE THREAD

**Issue by AhmadiGu** [AhmadiGu/Desktop_Portfolio#4]
- Add "alt" for images 
- Add the correct positions for images because I forgot to add the image folders 
- heading hierarchy fixed them
- contact form validation

**Comment by odaialazzeh** [comment]
good job, everything you added is working and nice done. 👏

**Comment by girma336** [comment]
Good job keep it up!!!

**Comment by rozhi-98** [comment]
-Great work on fixing all accessibility checks :white_check_mark:
-Contact form has all necessary validations :white_check_mark:
-Great job overall :clap:
